root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[env]
  HTTP_ADDR = ":8080"
  HTTP_PUBLIC_BASE = "http://localhost:8080"
  DB_DSN = "postgres://postgres:postgres@172.20.40.2:5432/postgres?sslmode=disable"
  JWT_SECRET = "CHANGE_ME_TO_RANDOM_STRING"
  JWT_TTL_MINUTES = "60"
  AMI_ADDR = "172.20.40.3:5038"
  AMI_USER = "asterisk"
  AMI_PASS = "asterisk"
  ASTERISK_RECORDING_URL = "http://172.20.40.3:8090/recordings"